//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityScanConfig) DeepCopyInto(out *CapabilityScanConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityScanConfig.
func (in *CapabilityScanConfig) DeepCopy() *CapabilityScanConfig {
	if in == nil {
		return nil
	}
	out := new(CapabilityScanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapabilityScanConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityScanConfigList) DeepCopyInto(out *CapabilityScanConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CapabilityScanConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityScanConfigList.
func (in *CapabilityScanConfigList) DeepCopy() *CapabilityScanConfigList {
	if in == nil {
		return nil
	}
	out := new(CapabilityScanConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapabilityScanConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityScanConfigSpec) DeepCopyInto(out *CapabilityScanConfigSpec) {
	*out = *in
	out.MCP = in.MCP
	if in.IncludeResources != nil {
		in, out := &in.IncludeResources, &out.IncludeResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeResources != nil {
		in, out := &in.ExcludeResources, &out.ExcludeResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Retry = in.Retry
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityScanConfigSpec.
func (in *CapabilityScanConfigSpec) DeepCopy() *CapabilityScanConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CapabilityScanConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityScanConfigStatus) DeepCopyInto(out *CapabilityScanConfigStatus) {
	*out = *in
	if in.LastScanTime != nil {
		in, out := &in.LastScanTime, &out.LastScanTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityScanConfigStatus.
func (in *CapabilityScanConfigStatus) DeepCopy() *CapabilityScanConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CapabilityScanConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventSelector) DeepCopyInto(out *EventSelector) {
	*out = *in
	if in.ConfidenceThreshold != nil {
		in, out := &in.ConfidenceThreshold, &out.ConfidenceThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventSelector.
func (in *EventSelector) DeepCopy() *EventSelector {
	if in == nil {
		return nil
	}
	out := new(EventSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitKnowledgeSource) DeepCopyInto(out *GitKnowledgeSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitKnowledgeSource.
func (in *GitKnowledgeSource) DeepCopy() *GitKnowledgeSource {
	if in == nil {
		return nil
	}
	out := new(GitKnowledgeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitKnowledgeSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitKnowledgeSourceList) DeepCopyInto(out *GitKnowledgeSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitKnowledgeSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitKnowledgeSourceList.
func (in *GitKnowledgeSourceList) DeepCopy() *GitKnowledgeSourceList {
	if in == nil {
		return nil
	}
	out := new(GitKnowledgeSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitKnowledgeSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitKnowledgeSourceSpec) DeepCopyInto(out *GitKnowledgeSourceSpec) {
	*out = *in
	in.Repository.DeepCopyInto(&out.Repository)
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.McpServer = in.McpServer
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MaxFileSizeBytes != nil {
		in, out := &in.MaxFileSizeBytes, &out.MaxFileSizeBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitKnowledgeSourceSpec.
func (in *GitKnowledgeSourceSpec) DeepCopy() *GitKnowledgeSourceSpec {
	if in == nil {
		return nil
	}
	out := new(GitKnowledgeSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitKnowledgeSourceStatus) DeepCopyInto(out *GitKnowledgeSourceStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.NextScheduledSync != nil {
		in, out := &in.NextScheduledSync, &out.NextScheduledSync
		*out = (*in).DeepCopy()
	}
	if in.SkippedFiles != nil {
		in, out := &in.SkippedFiles, &out.SkippedFiles
		*out = make([]SkippedFile, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitKnowledgeSourceStatus.
func (in *GitKnowledgeSourceStatus) DeepCopy() *GitKnowledgeSourceStatus {
	if in == nil {
		return nil
	}
	out := new(GitKnowledgeSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleChatConfig) DeepCopyInto(out *GoogleChatConfig) {
	*out = *in
	if in.WebhookUrlSecretRef != nil {
		in, out := &in.WebhookUrlSecretRef, &out.WebhookUrlSecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleChatConfig.
func (in *GoogleChatConfig) DeepCopy() *GoogleChatConfig {
	if in == nil {
		return nil
	}
	out := new(GoogleChatConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPCapabilityConfig) DeepCopyInto(out *MCPCapabilityConfig) {
	*out = *in
	out.AuthSecretRef = in.AuthSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPCapabilityConfig.
func (in *MCPCapabilityConfig) DeepCopy() *MCPCapabilityConfig {
	if in == nil {
		return nil
	}
	out := new(MCPCapabilityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McpRequest) DeepCopyInto(out *McpRequest) {
	*out = *in
	if in.ConfidenceThreshold != nil {
		in, out := &in.ConfidenceThreshold, &out.ConfidenceThreshold
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McpRequest.
func (in *McpRequest) DeepCopy() *McpRequest {
	if in == nil {
		return nil
	}
	out := new(McpRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McpServerConfig) DeepCopyInto(out *McpServerConfig) {
	*out = *in
	out.AuthSecretRef = in.AuthSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McpServerConfig.
func (in *McpServerConfig) DeepCopy() *McpServerConfig {
	if in == nil {
		return nil
	}
	out := new(McpServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfig) DeepCopyInto(out *NotificationConfig) {
	*out = *in
	in.Slack.DeepCopyInto(&out.Slack)
	in.GoogleChat.DeepCopyInto(&out.GoogleChat)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfig.
func (in *NotificationConfig) DeepCopy() *NotificationConfig {
	if in == nil {
		return nil
	}
	out := new(NotificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistenceConfig) DeepCopyInto(out *PersistenceConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistenceConfig.
func (in *PersistenceConfig) DeepCopy() *PersistenceConfig {
	if in == nil {
		return nil
	}
	out := new(PersistenceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimiting) DeepCopyInto(out *RateLimiting) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiting.
func (in *RateLimiting) DeepCopy() *RateLimiting {
	if in == nil {
		return nil
	}
	out := new(RateLimiting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationPolicy) DeepCopyInto(out *RemediationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationPolicy.
func (in *RemediationPolicy) DeepCopy() *RemediationPolicy {
	if in == nil {
		return nil
	}
	out := new(RemediationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationPolicyList) DeepCopyInto(out *RemediationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemediationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationPolicyList.
func (in *RemediationPolicyList) DeepCopy() *RemediationPolicyList {
	if in == nil {
		return nil
	}
	out := new(RemediationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationPolicySpec) DeepCopyInto(out *RemediationPolicySpec) {
	*out = *in
	if in.EventSelectors != nil {
		in, out := &in.EventSelectors, &out.EventSelectors
		*out = make([]EventSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.McpAuthSecretRef = in.McpAuthSecretRef
	if in.ConfidenceThreshold != nil {
		in, out := &in.ConfidenceThreshold, &out.ConfidenceThreshold
		*out = new(float64)
		**out = **in
	}
	out.RateLimiting = in.RateLimiting
	in.Notifications.DeepCopyInto(&out.Notifications)
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(PersistenceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationPolicySpec.
func (in *RemediationPolicySpec) DeepCopy() *RemediationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RemediationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationPolicyStatus) DeepCopyInto(out *RemediationPolicyStatus) {
	*out = *in
	if in.LastProcessedEvent != nil {
		in, out := &in.LastProcessedEvent, &out.LastProcessedEvent
		*out = (*in).DeepCopy()
	}
	if in.LastMcpMessageGenerated != nil {
		in, out := &in.LastMcpMessageGenerated, &out.LastMcpMessageGenerated
		*out = (*in).DeepCopy()
	}
	if in.LastRateLimitedEvent != nil {
		in, out := &in.LastRateLimitedEvent, &out.LastRateLimitedEvent
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationPolicyStatus.
func (in *RemediationPolicyStatus) DeepCopy() *RemediationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RemediationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryConfig) DeepCopyInto(out *RepositoryConfig) {
	*out = *in
	if in.Depth != nil {
		in, out := &in.Depth, &out.Depth
		*out = new(int)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryConfig.
func (in *RepositoryConfig) DeepCopy() *RepositoryConfig {
	if in == nil {
		return nil
	}
	out := new(RepositoryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSummary) DeepCopyInto(out *ResourceSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSummary.
func (in *ResourceSummary) DeepCopy() *ResourceSummary {
	if in == nil {
		return nil
	}
	out := new(ResourceSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSyncConfig) DeepCopyInto(out *ResourceSyncConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSyncConfig.
func (in *ResourceSyncConfig) DeepCopy() *ResourceSyncConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceSyncConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceSyncConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSyncConfigList) DeepCopyInto(out *ResourceSyncConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceSyncConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSyncConfigList.
func (in *ResourceSyncConfigList) DeepCopy() *ResourceSyncConfigList {
	if in == nil {
		return nil
	}
	out := new(ResourceSyncConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceSyncConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSyncConfigSpec) DeepCopyInto(out *ResourceSyncConfigSpec) {
	*out = *in
	out.McpAuthSecretRef = in.McpAuthSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSyncConfigSpec.
func (in *ResourceSyncConfigSpec) DeepCopy() *ResourceSyncConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSyncConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSyncConfigStatus) DeepCopyInto(out *ResourceSyncConfigStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.LastResyncTime != nil {
		in, out := &in.LastResyncTime, &out.LastResyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSyncConfigStatus.
func (in *ResourceSyncConfigStatus) DeepCopy() *ResourceSyncConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceSyncConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryConfig) DeepCopyInto(out *RetryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryConfig.
func (in *RetryConfig) DeepCopy() *RetryConfig {
	if in == nil {
		return nil
	}
	out := new(RetryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkippedFile) DeepCopyInto(out *SkippedFile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkippedFile.
func (in *SkippedFile) DeepCopy() *SkippedFile {
	if in == nil {
		return nil
	}
	out := new(SkippedFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackConfig) DeepCopyInto(out *SlackConfig) {
	*out = *in
	if in.WebhookUrlSecretRef != nil {
		in, out := &in.WebhookUrlSecretRef, &out.WebhookUrlSecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackConfig.
func (in *SlackConfig) DeepCopy() *SlackConfig {
	if in == nil {
		return nil
	}
	out := new(SlackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Solution) DeepCopyInto(out *Solution) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Solution.
func (in *Solution) DeepCopy() *Solution {
	if in == nil {
		return nil
	}
	out := new(Solution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Solution) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolutionContext) DeepCopyInto(out *SolutionContext) {
	*out = *in
	if in.Patterns != nil {
		in, out := &in.Patterns, &out.Patterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolutionContext.
func (in *SolutionContext) DeepCopy() *SolutionContext {
	if in == nil {
		return nil
	}
	out := new(SolutionContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolutionList) DeepCopyInto(out *SolutionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Solution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolutionList.
func (in *SolutionList) DeepCopy() *SolutionList {
	if in == nil {
		return nil
	}
	out := new(SolutionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SolutionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolutionSpec) DeepCopyInto(out *SolutionSpec) {
	*out = *in
	in.Context.DeepCopyInto(&out.Context)
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolutionSpec.
func (in *SolutionSpec) DeepCopy() *SolutionSpec {
	if in == nil {
		return nil
	}
	out := new(SolutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolutionStatus) DeepCopyInto(out *SolutionStatus) {
	*out = *in
	out.Resources = in.Resources
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolutionStatus.
func (in *SolutionStatus) DeepCopy() *SolutionStatus {
	if in == nil {
		return nil
	}
	out := new(SolutionStatus)
	in.DeepCopyInto(out)
	return out
}
